# Generated by Django 4.0.6 on 2022-08-03 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heading',
            old_name='Posted',
            new_name='posted',
        ),
        migrations.RenameField(
            model_name='heading',
            old_name='Title',
            new_name='title',
        ),
    ]
