# Generated by Django 4.0.6 on 2022-08-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_rename_posted_heading_posted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heading',
            name='posted',
        ),
    ]
