# Generated by Django 4.0.6 on 2022-08-03 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_context_title_txt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='text',
        ),
        migrations.AddField(
            model_name='context',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='heading',
            name='stuff',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='context',
            name='title_txt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.heading'),
        ),
    ]
