# Generated by Django 4.0.6 on 2022-08-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_context_title_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='type',
            field=models.CharField(default='Empty', max_length=10),
        ),
        migrations.AlterField(
            model_name='heading',
            name='title',
            field=models.CharField(default='Empty', max_length=50),
        ),
    ]
