# Generated by Django 4.0.6 on 2022-08-03 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_context_type_alter_heading_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='title_txt',
        ),
        migrations.AddField(
            model_name='heading',
            name='title_txt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.context'),
        ),
    ]
